livenessProbe:
  httpGet:
    port: 5000
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
readinessProbe:
  httpGet:
    port: 5000
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

postgres:
  host: postgres-service
  port: 5432
  dbName: postgres
  user: postgres
  password: postgres