{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "postgres.fullname" . }}-pv
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  {{- with .Values.persistence.accessModes }}
  accessModes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  hostPath:
    path: {{ .Values.persistence.hostPath }}
  persistentVolumeReclaimPolicy: Retain
{{- end }}