apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flask-app.fullname" . }}-secret
  namespace: default
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc | quote }}